run:
  go: "1.20"
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: vendor

linters:
  enable:
    - revive
    - gofmt
    - govet
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - goimports

linters-settings:
  govet:
    enable:
      - fieldalignment
    fieldalignment:
      fix: true

issues:
  exclude:
    - EXC0002 # Annoying issue about not having a comment
    - EXC0012 # func should have comment or be unexported
