name: lazylru
description: lazylru build pipeline

env:
  HOMEBREW_GITHUB_API_TOKEN: ${HOMEBREW_GITHUB_API_TOKEN}
  GITHUB_TOKEN: ${GITHUB_TOKEN}
  GOPRIVATE: github.com/TriggerMail

steps:
  - label: ":golang: test"
    artifact_paths: test-results/go-test-report.xml
    key: "test"
    plugins:
      - fanduel/gcr#v0.1.2:
          login: true
      - docker#v3.8.0:
          image: us.gcr.io/bluecore-ops/dockerfiles/golang:dev-1.17
          entrypoint: ""
          workdir: /app
          entrypoint: ""
          command:
          - scripts/ci/test.sh
          propagate-environment: true
          volumes:
            - "/root/.ssh/:/root/.ssh/"
  - label: ":golang: release"
    key: "release"
    agents:
      queue: vmserver
    command: ".buildkite/steps/release"
    plugins:
      - fanduel/gcr#v0.1.2:
          login: true
    if: build.tag =~ /v[0-9]+(\.[0-9]+)*(-.*)*/
    depends_on:
      - "test"
  - wait: ~
    continue_on_failure: true
  - plugins:
      - junit-annotate#v1.9.0:
          artifacts: test-results/go-test-report.xml