run:
  go: "1.18"
  timeout: 5m
  issues-exit-code: 1
  tests: true
  skip-dirs-use-default: true
  modules-download-mode: vendor

linters:
  disable:
    - structcheck # this is disabled because v1.45 is showing a lot of false positives
  enable:
    - revive
    - gofmt
    - govet
    - gosec
    - unconvert
    - goconst
    - gocyclo
    - goimports

linters-settings:
  govet:
    enable:
      - fieldalignment
    fieldalignment:
      fix: true
  revive:
    rules:
      - name: unused-parameter
        disabled: true

issues:
  exclude:
    - EXC0002 # Annoying issue about not having a comment
    - EXC0012 # func should have comment or be unexported
