name: go 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.23'

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Go Mod
      run: go mod download

    - name: Go Mod Verify
      run: go mod verify

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test --timeout=10s -v ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v6
      with:
        version: v1.60.3
        only-new-issues: true
