name: go 

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: 1.23

    - name: Go Tidy
      run: go mod tidy && git diff --exit-code

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test --count=1 --timeout=30s -v ./...

    - name: Lint code
      uses: golangci/golangci-lint-action@v6
      with:
        only-new-issues: true
